name: 🐛 DevOps Issue
description: รายงานปัญหาที่พบในการทำงานของระบบ
title: "[Issue] <ระบุชื่อ Issue ที่เข้าใจได้>"
labels: ["aws-issue", "azure-issue", "system-issue", "jenkins-issue", "kubernetes-issue"]
projects: ["scbconnect", "j4u", "merchant", "rpt"]
body:
  # 1. Dropdown สำหรับการจัดประเภทปัญหา (Category)
  - type: dropdown
    id: category
    attributes:
      label: ประเภทของปัญหา (Issue Category)
      description: กรุณาเลือกประเภทของปัญหาที่เกิดขึ้น
      options:
        - Jenkins-failure
        - Disk
        - Resource
        - Cloud
    validations:
      required: true
      
  # 2. Checkboxes สำหรับการยืนยัน
  - type: checkboxes
    id: required_checks
    attributes:
      label: การตรวจสอบเบื้องต้น (Pre-Check)
      description: กรุณายืนยันว่าคุณได้ดำเนินการตรวจสอบเบื้องต้นแล้ว
      options:
        - label: ฉันได้ค้นหา Issue ที่คล้ายกันแล้ว แต่ไม่พบ
          required: true
        - label: ฉันได้ลองทำซ้ำขั้นตอนแล้ว และปัญหายังคงอยู่
          required: true

  # 3. Text Area สำหรับ Steps to Reproduce
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: ขั้นตอนการเกิดปัญหา (Steps to Reproduce)
      description: โปรดระบุขั้นตอนโดยละเอียดที่ทำให้เกิดปัญหา
      placeholder: |
        1. ไปที่หน้า X
        2. คลิกปุ่ม Y
        3. ปัญหา Z เกิดขึ้น
    validations:
      required: true
