name: Auto Move Project Card
on:
  issues:
    types: [labeled, assigned]

permissions:
  contents: read

jobs:
  # -----------------------------------------------
  # 1. TODO: เมื่อ n8n Flow 1 ติด Label 'Todo'
  # -----------------------------------------------
  move_to_todo:
    if: github.event.action == 'labeled' && github.event.label.name == 'Todo'
    runs-on: ubuntu-latest
    
    steps:
      - name: Set Status to Todo
        # *** เปลี่ยนไปใช้ Action ที่เสถียรและได้รับความนิยม (จาก Marketplace) ***
        uses: actions/github-script@v6 
        with:
          # Project ID ที่คุณหามาได้
          project-id: PVT_kwHOAhgQ884BGiVe 
          # ID ของ Item ที่จะอัพเดต (ได้มาจาก Payload ของ Issue Event)
          issue-id: ${{ github.event.issue.node_id }} 
          # ค่าใหม่ที่ต้องการ (ต้องตรงกับชื่อ Status Column ใน Board)
          status-value: Todo 
          # *** ใช้ Secret ที่มีสิทธิ์เข้าถึง User Project (PROJECT_PAT) ***
          github-token: ${{ secrets.PROJECT_PAT }} 

  # -----------------------------------------------
  # 2. IN PROGRESS: เมื่อ n8n Flow 2 Assign Engineer
  # -----------------------------------------------
  move_to_in_progress:
    if: github.event.action == 'assigned'
    runs-on: ubuntu-latest
    
    steps:
      - name: Set Status to In Progress
        uses: actions/github-script@v6
        with:
          project-id: PVT_kwHOAhgQ884BGiVe 
          issue-id: ${{ github.event.issue.node_id }} 
          status-value: 'In Progress' # ต้องตรงกับชื่อ Status Column ใน Board
          github-token: ${{ secrets.PROJECT_PAT }}