name: Auto Move Project Card
on:
  issues:
    types: [labeled, assigned]

jobs:
  # -----------------------------------------------
  # 1. TODO: เมื่อ n8n Flow 1 ติด Label 'Todo'
  # -----------------------------------------------
  move_to_todo:
    if: github.event.action == 'labeled' && github.event.label.name == 'Todo'
    runs-on: ubuntu-latest
    
    steps:
      - name: Set Status to Todo
        # *** ใช้ Action สำเร็จรูปที่ออกแบบมาเพื่อ Project V2 field update โดยเฉพาะ ***
        # Note: Actions ตัวนี้ไม่ใช่ของทางการ แต่ถูกออกแบบมาเพื่อแก้ปัญหานี้โดยตรง
        uses: edgard/set-project-v2-field-action@v1 
        with:
          # ใส่ Project ID ที่คุณหามาได้
          project-id: PVT_kwHOAhgQ884BGiVe 
          # ID ของ Item ที่จะอัพเดต (ได้มาจาก Payload ของ Issue Event)
          issue-id: ${{ github.event.issue.node_id }} 
          # ชื่อ Field ที่ต้องการอัพเดต (คือ Status)
          field-name: Status 
          # ค่าใหม่ที่ต้องการ (คือ Todo)
          value: Todo
          github-token: ${{ secrets.ISSSUE_GITHUB_TOKEN }}

  # -----------------------------------------------
  # 2. IN PROGRESS: เมื่อ n8n Flow 2 Assign Engineer
  # -----------------------------------------------
  move_to_in_progress:
    if: github.event.action == 'assigned'
    runs-on: ubuntu-latest
    
    steps:
      - name: Set Status to In Progress
        uses: edgard/set-project-v2-field-action@v1 
        with:
          project-id: PVT_kwHOAhgQ884BGiVe 
          issue-id: ${{ github.event.issue.node_id }} 
          field-name: Status 
          value: In Progress
          github-token: ${{ secrets.ISSSUE_GITHUB_TOKEN }}