name: Auto Move Project Card
# Action นี้จะทำงานเมื่อมี Event เกี่ยวกับ Issue เกิดขึ้นเท่านั้น (เปิด, ติด Label, Assign)
on:
  issues:
    types: [labeled, assigned]

jobs:
  # -----------------------------------------------
  # 1. TODO: เมื่อ n8n Flow 1 ติด Label 'Todo'
  # -----------------------------------------------
  move_to_todo:
    # เงื่อนไข: ให้รัน Job นี้เฉพาะเมื่อ Label ที่ถูกเพิ่มคือ 'Todo' เท่านั้น
    if: github.event.action == 'labeled' && github.event.label.name == 'Todo'
    runs-on: ubuntu-latest
    
    steps:
      - name: Move Issue to 'Todo' column
        # ใช้ Action สำเร็จรูปในการจัดการ Project Board
        uses: alex-page/github-project-card-automation@v1 
        with:
          # (!!! สำคัญ: ต้องใส่ชื่อ Project ของคุณแทนที่ข้อความนี้)
          project: 'DevOps-Issue' 
          column: 'Todo'
          # GITHUB_TOKEN มีอยู่แล้ว ไม่ต้องสร้าง Secret ใหม่
          token: ${{ secrets.GITHUB_TOKEN }}

  # -----------------------------------------------
  # 2. IN PROGRESS: เมื่อ n8n Flow 2 Assign Engineer
  # -----------------------------------------------
  move_to_in_progress:
    # เงื่อนไข: ให้รัน Job นี้เฉพาะเมื่อ Issue ถูก 'assigned' เท่านั้น
    if: github.event.action == 'assigned'
    runs-on: ubuntu-latest
    
    steps:
      - name: Move Issue to 'In Progress' column
        uses: alex-page/github-project-card-automation@v1
        with:
          # (!!! สำคัญ: ต้องใส่ชื่อ Project ของคุณแทนที่ข้อความนี้)
          project: 'DevOps-Issue' 
          column: 'In Progress'
          token: ${{ secrets.GITHUB_TOKEN }}