name: Auto Move Project Card
on:
  issues:
    types: [labeled, assigned, opened]

jobs:
  # -----------------------------------------------
  # 1. TODO: เมื่อ n8n Flow 1 ติด Label 'Todo'
  # -----------------------------------------------
  move_to_todo:
    # เงื่อนไข: ให้รัน Job นี้เฉพาะเมื่อ Label 'Todo' ถูกเพิ่ม
    if: github.event.action == 'labeled' && github.event.label.name == 'Todo'
    runs-on: ubuntu-latest
    
    steps:
      - name: Add to Project Board
        # ใช้ Action ที่เป็นทางการของ GitHub
        uses: actions/add-to-project@v0.5.0 
        with:
          # *** แก้ไข: ใช้ Project URL ในรูปแบบที่ Action ต้องการ ***
          # รูปแบบ: https://github.com/users/ownerName/projects/projectNumber
          project-url: 'https://github.com/users/nopponcha/projects/2' 
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
  # -----------------------------------------------
  # 2. IN PROGRESS: เมื่อ n8n Flow 2 Assign Engineer
  # -----------------------------------------------
  move_to_in_progress:
    # เงื่อนไข: ให้รัน Job นี้เฉพาะเมื่อ Issue ถูก 'assigned'
    if: github.event.action == 'assigned'
    runs-on: ubuntu-latest
    
    steps:
      - name: Update Project Status to 'In Progress'
        # Action สำหรับย้าย Status โดยตรงนั้นซับซ้อนกว่า (ต้องใช้ API)
        # Action 'actions/add-to-project' ทำได้แค่เพิ่ม Item เข้า Board
        # การเปลี่ยน Status จะต้องตั้งค่าใน Workflows UI
        run: echo "Item added to project. Please set 'In Progress' move rule in GitHub Projects UI."