name: Auto Move Project Card
on:
  issues:
    types: [labeled, assigned]

permissions:
  contents: read
  issues: write
  pull-requests: write

env:
  # Project ID ใหม่ที่ถูกต้อง
  PROJECT_ID: PVT_kwHOAhgQ884BGnf5
  
jobs:
  # -----------------------------------------------
  # 1. TODO: เมื่อ Issue ถูกติด Label 'Todo'
  # -----------------------------------------------
  move_to_todo:
    if: github.event.action == 'labeled' && github.event.label.name == 'Todo'
    runs-on: ubuntu-latest
    
    steps:
      - name: Set Status to Todo via GraphQL
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PROJECT_PAT }} 
          script: |
            const PROJECT_ID = process.env.PROJECT_ID;
            const CONTENT_ID = context.payload.issue.node_id;

            // ----------------------------------------------------
            // **ขั้นตอนที่ 1: เพิ่ม Issue เข้า Project V2 ก่อน**
            // แก้ปัญหา 'Could not resolve to ProjectV2Item node'
            // ----------------------------------------------------
            core.info(`Adding item ${CONTENT_ID} to project ${PROJECT_ID}...`);
            await github.graphql(`
              mutation addProjectItem($projectId: ID!, $contentId: ID!) {
                addProjectV2ItemById(input: {
                  projectId: $projectId,
                  contentId: $contentId
                }) {
                  item { id }
                }
              }
            `, {
              projectId: PROJECT_ID,
              contentId: CONTENT_ID,
            });
            core.info(`Item added successfully.`);


            // ----------------------------------------------------
            // **ขั้นตอนที่ 2: อัปเดตสถานะเป็น Todo**
            // ----------------------------------------------------
            
            // 2.1 ค้นหา Field ID และ Option ID ของ Status:Todo
            const projectRes = await github.graphql(`
              query getProjectFields($id: ID!) {
                node(id: $id) {
                  ... on ProjectV2 {
                    fields(first: 20) {
                      nodes {
                        ... on ProjectV2SingleSelectField { id name options { id name } }
                      }
                    }
                  }
                }
              }`, { id: PROJECT_ID });
            
            const statusField = projectRes.node.fields.nodes.find(f => f.name === 'Status');
            
            // การตรวจสอบข้อผิดพลาด 1: Field Name
            if (!statusField) {
              core.setFailed("Error: 'Status' field not found. Check Field Name and case sensitivity in Project Settings.");
              return; 
            }
            
            const statusFieldId = statusField.id;
            const todoOption = statusField.options.find(o => o.name === 'Todo'); // ใช้ 'Todo' ตามโค้ดล่าสุด
            
            // การตรวจสอบข้อผิดพลาด 2: Option Name
            if (!todoOption) {
              core.setFailed("Error: 'Todo' option not found in Status field. Check Option Name and case sensitivity in Project Settings.");
              return;
            }
            const todoOptionId = todoOption.id;

            // 2.2 ทำการ Mutation เพื่อ Update Status
            // NOTE: เราใช้ CONTENT_ID เป็น itemId ใน ProjectV2ItemFieldValue mutation ได้
            await github.graphql(`
              mutation updateProjectStatus($projectId: ID!, $itemId: ID!, $fieldId: ID!, $optionId: String!) {
                updateProjectV2ItemFieldValue(input: {
                  projectId: $projectId,
                  itemId: $itemId,
                  fieldId: $fieldId,
                  value: { singleSelectOptionId: $optionId }
                }) {
                  projectV2Item { id }
                }
              }`, {
              projectId: PROJECT_ID,
              itemId: CONTENT_ID,
              fieldId: statusFieldId,
              optionId: todoOptionId,
            });
            
            core.info(`Successfully set item status to: Todo`);

  # -----------------------------------------------
  # 2. IN PROGRESS: เมื่อ Assign Engineer
  # -----------------------------------------------
  move_to_in_progress:
    if: github.event.action == 'assigned'
    runs-on: ubuntu-latest
    
    steps:
      - name: Set Status to In Progress via GraphQL
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PROJECT_PAT }} 
          script: |
            const PROJECT_ID = process.env.PROJECT_ID;
            const CONTENT_ID = context.payload.issue.node_id;

            // ----------------------------------------------------
            // **ขั้นตอนที่ 1: เพิ่ม Issue เข้า Project V2 ก่อน**
            // ----------------------------------------------------
            core.info(`Adding item ${CONTENT_ID} to project ${PROJECT_ID}...`);
            await github.graphql(`
              mutation addProjectItem($projectId: ID!, $contentId: ID!) {
                addProjectV2ItemById(input: {
                  projectId: $projectId,
                  contentId: $contentId
                }) {
                  item { id }
                }
              }
            `, {
              projectId: PROJECT_ID,
              contentId: CONTENT_ID,
            });
            core.info(`Item added successfully.`);
            
            // ----------------------------------------------------
            // **ขั้นตอนที่ 2: อัปเดตสถานะเป็น In Progress**
            // ----------------------------------------------------
            
            // 2.1 ค้นหา Field ID และ Option ID ของ Status:In Progress
            const projectRes = await github.graphql(`
              query getProjectFields($id: ID!) {
                node(id: $id) {
                  ... on ProjectV2 {
                    fields(first: 20) {
                      nodes {
                        ... on ProjectV2SingleSelectField { id name options { id name } }
                      }
                    }
                  }
                }
              }`, { id: PROJECT_ID });
            
            const statusField = projectRes.node.fields.nodes.find(f => f.name === 'Status');
            
            // การตรวจสอบข้อผิดพลาด 1: Field Name
            if (!statusField) {
              core.setFailed("Error: 'Status' field not found. Check Field Name and case sensitivity in Project Settings.");
              return; 
            }
            
            const statusFieldId = statusField.id;
            const inProgressOption = statusField.options.find(o => o.name === 'In Progress');
            
            // การตรวจสอบข้อผิดพลาด 2: Option Name
            if (!inProgressOption) {
              core.setFailed("Error: 'In Progress' option not found in Status field. Check Option Name and case sensitivity in Project Settings.");
              return;
            }
            const inProgressOptionId = inProgressOption.id;

            // 2.2 ทำการ Mutation เพื่อ Update Status
            await github.graphql(`
              mutation updateProjectStatus($projectId: ID!, $itemId: ID!, $fieldId: ID!, $optionId: String!) {
                updateProjectV2ItemFieldValue(input: {
                  projectId: $projectId,
                  itemId: $itemId,
                  fieldId: $fieldId,
                  value: { singleSelectOptionId: $optionId }
                }) {
                  projectV2Item { id }
                }
              }`, {
              projectId: PROJECT_ID,
              itemId: CONTENT_ID,
              fieldId: statusFieldId,
              optionId: inProgressOptionId,
            });
            
            core.info(`Successfully set item status to: In Progress`);